### ISSUE TITLE
ValueError: Only numeric, Timestamp and Timedelta endpoints are allowed when constructing an Interval.

### ISSUE THREAD

**Issue by wuziniu** [MaxHalford/phd#1]
Hi Max,

When constructing the histogram for categorical data in tools.categorical_qcut function, line 54 causes a ValueError. 
Line 54: interval = pd.Interval(left=values_in_bin[0], right=values_in_bin[-1], closed='both')
ValueError: Only numeric, Timestamp and Timedelta endpoints are allowed when constructing an Interval.
The values_in_bin are not numeric, for example in my case, they are value from i_formulation in item table. (something like: "000026red49169482502","03545247747774smoke8")
Thus how should I discretize this attribute.

**Comment by MaxHalford** [comment]
Hey there.

The way to work around this would be to encode your categorical variables with numbers. For instance `000026red49169482502` becomes 0, `03545247747774smoke8` becomes 1, etc.

**Comment by wuziniu** [comment]
Thank you Max. That would work. However, for most other attributes, this error doesn't appear. Can I know which version of postregsql are you using? Since some attributes (like this one) contain data that doesn't make a lot of sense after populating the data using cli.py file.

**Comment by wuziniu** [comment]
That will work. Thanks a lot.
